apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: elk
  name: elasticsearch-data
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      component: elasticsearch
      role: data
