apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: elk
  name: elastic-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 50Gi
