kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: elk
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: elk
  name: system:azure-cloud-provider
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs:     ['get','create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: elk
  name: system:azure-cloud-provider
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:azure-cloud-provider
subjects:
  - kind: ServiceAccount
    name: persistent-volume-binder
    namespace: kube-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: elk
  name: elastic-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 50Gi
