apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: logstash
spec:
  type: ClusterIP
  selector:
    component: logstash
  ports:
    - name: beats
      port: 5044
      targetPort: 5044
    - name: tcp
      port: 5010
      targetPort: 5010
