apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kube-system
  name: metricbeat-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
