apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: elk
  name: system:azure-cloud-provider
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs:     ['get','create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: elk
  name: system:azure-cloud-provider
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:azure-cloud-provider
subjects:
  - kind: ServiceAccount
    name: persistent-volume-binder
    namespace: kube-system
