apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: kibana-dashboard
  labels:
    app: kibana
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  selector:
    app: kibana
  ports:
    - port: 80
      name: http
      targetPort: 5601
