apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: logstash-service
spec:
  type: ClusterIP
  selector:
    component: logstash
  ports:
    - name: beats
      port: 5044
      targetPort: 5044
