apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: elk
  name: elasticsearch-master
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: elasticsearch
      role: master
